# Jekyll Config

# Site settings
title: Founderland
description: "WE'RE BUILDING A NEW INCLUSIVE AND INTERSECTIONAL STANDARD FOR ENTREPRENEURS"
baseurl: '/' # the subpath of your site, e.g. /blog
url: 'https://founderland.github.io' # the base hostname & protocol for your site

# Build settings
exclude:
  - package.json
  - package-lock.json
  - README.md
  - CNAME
  - tailwind.config.js
  - assets/styles/main_dev.css
